version: "2.3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: kumparan-container-api
    ports:
      - "9000:9000"
    depends_on:
      - redis
  redis:
    container_name: kumparan-container-redis
    image: redis:7.0.0-alpine
    ports:
      - "6378:6379"
